#!/usr/bin/env bash

set -e

APP="/app/www"
CONFIG="/config"

cd $APP

# ----------------------------
# 1. Database always from config
# ----------------------------
mkdir -p "$APP/database"
touch "$CONFIG/database.sqlite"
ln -sfn "$CONFIG/database.sqlite" "$APP/database/database.sqlite"

# ----------------------------
# 2. Fix Storage & Permissions
# ----------------------------
mkdir -p /app/www/storage/framework/views
mkdir -p /app/www/storage/framework/cache/data
mkdir -p /app/www/storage/framework/sessions
mkdir -p /app/www/storage/framework/testing
mkdir -p /app/www/storage/app/private
mkdir -p /app/www/storage/app/public
mkdir -p /app/www/storage/logs
chmod -R 775 /app/www/storage

chown -R sail:sail $CONFIG || true
chown -R sail:sail $APP || true

gosu sail php artisan config:clear || true

# ----------------------------
# 3. Migrate safely
# ----------------------------
gosu sail php artisan migrate --force || true

# ----------------------------
# 4. Start
# ----------------------------
exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf